#server:
#  port: 8080
#  servlet:
#    context-path:
#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/hibernateTest?user=postgres&currentSchema=public
#    password: 1234
#    username: postgres
#  jpa:
#    database: POSTGRESQL
#    generate-ddl: true
#    hibernate.ddl-auto: create
#    properties:
#      hibernate:
#        temp:
#          use_jdbc_metadata_defaults: false
#      database-platform: org.hibernate.dialect.PostgreSQL9Dialect
#



jwt:
  secret: '[a-zA-Z0-9._]^+$Guidelines89797987forAlphabeticalArraNumeralsandOtherSymbo$'


server:
  port: 8080
  servlet:
    context-path:
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myschema
    username: root
    password: root
  jpa:
    database: mysql
    hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: true


  mail:
    host: smtp.gmail.com
    port: 587
    username: marrymebelgium@gmail.com
    password: joruixbmwjndohev
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true
