server:
  port: 8080
  servlet:
    context-path:
#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/hibernateTest?user=postgres&currentSchema=public
#    password: 1234
#    username: postgres
#  jpa:
#    database: POSTGRESQL
#    generate-ddl: true
#    hibernate.ddl-auto: create
#    properties:
#      hibernate:
#        temp:
#          use_jdbc_metadata_defaults: false
#      database-platform: org.hibernate.dialect.PostgreSQL9Dialect
#

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myschema
    username: root
    password: root
  jpa:
    database: mysql
    hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: true

